[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.33.0"
dist = false
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
]
ci = []
installers = []
precise-builds = true
unix-archive = ".tar.gz"
checksum = "sha256"
auto-includes = false
include = ["LICENSE"]
