[package]
name = "semantic-engine"
description = "DataFusion-backed sessions, source registration, and derived relations"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
semantic-materialization.workspace = true
serde.workspace = true
semantic-runtime.workspace = true
semantic-catalog.workspace = true
datafusion.workspace = true
datafusion-federation.workspace = true
thiserror.workspace = true

futures.workspace = true
async-stream.workspace = true

[dev-dependencies]

[lints]
workspace = true
