[package]
name = "example-github"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
semantic-db = { workspace = true, default-features = false, features = ["sources", "github"] }
tokio.workspace = true

[lints]
workspace = true
