[package]
name = "semantic-cli"
description = "Interactive SQL frontend for Semantic DB"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "semantic-db"
path = "src/main.rs"

[dependencies]
semantic-engine.workspace = true
semantic-compiler.workspace = true
semantic-ossie.workspace = true
dotenvy.workspace = true
clap.workspace = true
rustyline.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
